#Global configurations

#Tudo que for configurado nesta área vale para todos os perfis de start de aplicação.

#Use esta área para incluir as configurações para ambiente de desenvolvimento (sem perfil definido).

configurations:
  typeconfig: Esse é uma configuração global para o ambiente de desenvolvimento.

#Propriedades do banco de dados H2
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: create
    properties.hibernate.hbm2ddl.import_files: scripts/create_data.sql
  datasource:
    url: jdbc:h2:~/db-h2/userDB
    username: sa
    password:
    driver-class-name: org.h2.Driver

#Propriedades do banco de dados MySQL
#spring:
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    ddl-auto: create
#    properties.hibernate.hbm2ddl.import_files: scripts/create_data.sql
#  datasource:
#    url: jdbc:mysql://localhost:3306/userDB
#    username: root
#    password: user123
#    driver-class-name: com.mysql.jdbc.Driver

---

#Use esta área para incluir as configurações para ambiente de teste.
spring:
  profiles: staging  

configurations:
  typeconfig: Esse é uma configuração global para o ambiente de staging.

---

#Use esta área para incluir as configurações para ambiente de produção.
spring:
  profiles: production  

configurations:
  typeconfig: Esse é uma configuração global para o ambiente de produção.