#Microservice authentication-server Configurations

#Tudo que for configurado nesta área vale para todos os perfis de start de aplicação.

#Use esta área para incluir as configurações para ambiente de desenvolvimento (sem perfil definido).
server:
  port: 8080
#  contextPath: /uaa

spring.h2.console.enabled: true
spring.h2.path: /h2

spring:
  jpa:
    database-platform: ${spring.jpa.database-platform}
    ddl-auto: ${spring.jpa.ddl-auto}
    properties.hibernate.hbm2ddl.import_files: ${spring.jpa.properties.hibernate.hbm2ddl.import_files}
  datasource:
    driverClassName: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  mail:
    host: smtp.gmail.com
    port: 587

spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

configurations.authentication-server:
  redirecturl: http://localhost:3000
  url: http://localhost:8080/uaa

# JWT
jwt:
  secret: user_secret
# expiration 7 days
  expiration: 604800

---

#Use esta área para incluir as configurações para ambiente de teste.
spring:
  profiles: staging  
  
---

#Use esta área para incluir as configurações para ambiente de produção.
spring:
  profiles: production  